os: linux
dist: trusty
sudo: required
before_install:
- export DEVKITPRO=/home/travis/devkitPro
- export DEVKITARM=${DEVKITPRO}/devkitARM
- export PATH=$PATH:${DEVKITARM}/bin
- curl -L https://raw.githubusercontent.com/devkitPro/installer/master/perl/devkitARMupdate.pl
  -o devkitARMupdate.pl
- chmod +x ./devkitARMupdate.pl
- chmod +x $TRAVIS_BUILD_DIR/buildtools/3ds/*
install:
- "./devkitARMupdate.pl /home/travis/devkitPro"
- git clone https://github.com/smealum/ctrulib
- git clone https://github.com/fincs/citro3d
- cd ctrulib/libctru
- make -j4
- sudo -E make install
- cd ../..
- cd citro3d
- git checkout next
- make -j4
- sudo -E make install
- cd $TRAVIS_BUILD_DIR
- wget --no-check-certificate https://raw.githubusercontent.com/libretro/RetroArch/master/ctr/tools/bannertool-linux
- chmod +x bannertool-linux
- sudo mv bannertool-linux buildtools/3ds/bannertool-linux64
- sudo chmod +x ./deps.sh
- "./deps.sh"
- cd
script:
- cd $TRAVIS_BUILD_DIR
- sed -i "s/-DVERSION='\".*\"'/-DVERSION='\"$(echo $TRAVIS_COMMIT | cut -c -7)-git\"'/" Makefile
- make -j
after_success:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm init -y; npm install github; node ./.travis-upload.js; fi'
addons:
  apt:
    packages:
    - libstdc++6
